[workspace]
resolver = "2"
members = [
    "combination_sum",
    "combination_sum_2",
    "combination_sum_3",
    "combine",
    "letter_combinations_of_phone_number", "restore_ip_addresses", "sliced_to_palindrome",
]
