[workspace]
resolver = "2"
members = [
    "combination_sum",
    "combination_sum_2",
    "combination_sum_3",
    "combine",
    "letter_combinations_of_phone_number", "non_decreasing_subsequence", "permute", "restore_ip_addresses", "sliced_to_palindrome", "subset", "subset_with_duplicate",
]
